CREATE TABLE pharmacy_data (
    medication VARCHAR(255),
    disease VARCHAR(255)
);

INSERT INTO pharmacy_data (medication, disease) VALUES
('Metformin', 'Type 2 Diabetes'),
('Lisinopril', 'Hypertension'),
('Atorvastatin', 'High Cholesterol'),
('Levothyroxine', 'Hypothyroidism'),
('Albuterol', 'Asthma'),
('Amlodipine', 'Hypertension'),
('Metoprolol', 'Angina'),
('Omeprazole', 'GERD'),
('Losartan', 'Hypertension'),
('Sertraline', 'Depression'),
('Gabapentin', 'Nerve Pain'),
('Hydrochlorothiazide', 'Edema'),
('Ativan', 'Anxiety'),
('Furosemide', 'Heart Failure'),
('Pantoprazole', 'Stomach Acid'),
('Acetaminophen', 'Chronic Pain'),
('Prednisone', 'Inflammation'),
('Amoxicillin', 'Bacterial Infection'),
('Fluoxetine', 'Obsessive-Compulsive Disorder'),
('Meloxicam', 'Osteoarthritis'),
('Warfarin', 'Blood Clots'),
('Clopidogrel', 'Heart Attack Prevention'),
('Montelukast', 'Allergic Rhinitis'),
('Escitalopram', 'Generalized Anxiety Disorder'),
('Rosuvastatin', 'Hyperlipidemia'),
('Bupropion', 'Smoking Cessation'),
('Duloxetine', 'Fibromyalgia'),
('Ranitidine', 'Heartburn'),
('Venlafaxine', 'Panic Disorder'),
('Zolpidem', 'Insomnia'),
('Empagliflozin', 'Type 2 Diabetes'),
('Valsartan', 'Heart Failure'),
('Tamsulosin', 'Benign Prostatic Hyperplasia'),
('Spironolactone', 'Acne'),
('Naproxen', 'Rheumatoid Arthritis'),
('Memantine', 'Alzheimer''s Disease'),
('Donepezil', 'Dementia'),
('Methotrexate', 'Psoriasis'),
('Adalimumab', 'Crohn''s Disease'),
('Infliximab', 'Ulcerative Colitis'),
('Sumatriptan', 'Migraine'),
('Finasteride', 'Hair Loss'),
('Latanoprost', 'Glaucoma'),
('Oxybutynin', 'Overactive Bladder'),
('Rivaroxaban', 'Deep Vein Thrombosis'),
('Apixaban', 'Atrial Fibrillation'),
('Metronidazole', 'Bacterial Vaginosis'),
('Fluconazole', 'Yeast Infection'),
('Acyclovir', 'Herpes Simplex'),
('Azithromycin', 'Pneumonia');
